services:
  backend:
    build: ./backend
    container_name: becas-backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/becasdb
    depends_on:
      mongo:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - /app/node_modules
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: becas-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped

  mongo:
    image: mongo:7.0
    container_name: becas-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: becasdb
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/becasdb --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
